title: Joshua D. Chen
description: > 
  Write your awesome description for your site here, and it will appear in the meta
  description tag in the head section of your site!

baseurl: "chenjoshua7.github.io"
url: ""

theme: minima
plugins:
  - jekyll-feed

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/